# @package hydra.sweeper
defaults:
  - base
  - fio
  - prefetch
  - client-bp
  - client
  - crt

_target_: hydra_plugins.smart_sweeper.smart_benchmark_sweeper.SmartBenchmarkSweeper
max_batch_size: null