name: Integration tests (PR)

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'benchmark_website/**'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration-codebuild.yml
    with:
      environment: PR integration tests
      ref: ${{ github.event.pull_request.head.sha }}
